## Docker 配置 Secret 
# https://kubernetes.io/zh/docs/concepts/configuration/secret/
# 
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
        "<base64 encoded ~/.dockercfg file>"