apiVersion: v1
kind: Pod
metadata:
  name: examplepodforreadiness
spec:
  containers:
    - name: readinesscontainer
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: portfornginx
          containerPort: 80
      readinessProbe:
        httpGet:
          port: 80
          path: /