# https://kubernetes.io/zh/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mysvcnode
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8001

# kubectl --namespace default port-forward --address 0.0.0.0 service/mysvcnode 8080:80