# https://raw.githubusercontent.com/kubernetes/website/main/content/zh/examples/pods/storage/pv-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: task-pv-container
    image: nginx:alpine
    ports:
      - containerPort: 80
