apiVersion: v1
kind: ReplicationController
metadata:
  name: flower-controller
  labels:
    component: flower

spec:
  replicas: 1
  selector:
    app: myapp
  template:
    metadata:
      name: flower
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
        - name: flower
          image: endocode/flower
          ports:
            - containerPort: 5555
