apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    component: flower

spec:
  selector:
    app: taskQueue
    component: flower 
  ports:
  - port: 5555
    targetPort: 5555

#  kubectl --namespace default port-forward --address 0.0.0.0  service/flower-service 8080:5555