apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    component: flower

spec:
  selector:
    app: mtaskQueue
    component: flower 
  ports:
  - port: 5555
    targetPort: 5555
