apiVersion: v1
kind: Pod
metadata:
  name: examplepodforpoststartandprestop
spec:
  containers:
  - name: poststartandprestop-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c']
    args: ['echo "Hello Kubernetes!"; sleep 3600']
    lifecycle:
      postStart:
        httpGet:
          host: www.baiduxx.com
          path: /
          port: 80
          scheme: HTTP
      preStop:
        exec:
          command: ['sh', '-c', 'echo "preStop callback done!"; sleep 60']
    restartPolicy: OnFailure