# https://kubernetes.io/docs/concepts/workloads/pods/
# 配置环境变量
apiVersion: v1
kind: Pod
metadata:
  name: "cm-test"
  namespace: default
  labels:
    app: "myapp-cm-env"
spec:
  containers:
  - name: myapp-volume-test
    image: "busybox"
    command: ["/bin/sh", "-c", "ls /etc/config"]
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi
    volumes:
      - name: config-volume
        configMap:
          name: app-config

  restartPolicy: Always
---
