# https://kubernetes.io/docs/concepts/workloads/pods/
# 配置环境变量
apiVersion: v1
kind: Pod
metadata:
  name: "cm-test-from"
  namespace: default
  labels:
    app: "myapp-cm-from"
spec:
  containers:
  - name: myapp-from-test
    image: "busybox"
    command: ["/bin/sh", "-c", "echo $()"]
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi
    env:
    - name: LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: app.how
  
  restartPolicy: Always
---
