# https://kubernetes.io/docs/concepts/workloads/pods/
# 配置环境变量
apiVersion: v1
kind: Pod
metadata:
  name: "cm-test-file"
  namespace: default
  labels:
    app: "myapp-cm-file"
spec:
  volumes:
    - name: config
      configMap:
        name: app-config
        # 来自 ConfigMap 的一组键，将被创建为文件. 默认全部挂载.items 指定挂载
        # items:
  restartPolicy: Always
  containers:
  - name: myapp-volume-test
    image: "busybox"
    command: ["/bin/sh", "-c", "ls -l /etc/config"]
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi
    volumeMounts:
      - name: config
        mountPath: /etc/config
---
