# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "configmap-demo-pod"
  namespace: default
  labels:
    app: "configmap-demo-pod"
spec:
  containers:
  - name: configmap-demo-container
    image: alpine
    command:
      - "sleep"
      - "3600"
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 20Mi
    env:
    # # 定义环境变量
    - name: PLAYER_INITIAL_LIVES # 请注意这里和 ConfigMap 中的键名是不一样的
      valueFrom:
        configMapKeyRef:
          name: game-demo
          key: player_initial_lives # 需要取值的键
    - name: UI_PROPERTIES_FILE_NAME
      valueFrom:
        configMapKeyRef:
          name: game-demo
          key: ui_properties_file_name 
    ports:
    - containerPort: 80
      name:  http
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo
        # # 来自 ConfigMap 的一组键，将被创建为文件
        items:
          - key: "game.properties"
            path: "game.properties"
          - key: "user-interface.properties"
            path: "user-interface.properties"
        
  restartPolicy: Always
---
