apiVersion: v1
kind: Pod
metadata:
  name: mylabel
  labels:
    name: mylabel
    env: test
    role: test
spec:
  containers:
  - name: mylabel
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
