apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-demo-emptydir
  labels:
    name: pod-volume-demo-emptydir
spec:
  containers:
  - name: myapp-pod-emptydir
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
  volumes:
    - name: cache-volume
      # worker 节点的主机
      # /var/lib/kubelet/pods/uid/volumes/kubernetes.io\~empty-dir/cache-volume
      emptyDir: {}
        
