#https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: [ "perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)" ]
      - name: hello
        image: busybox
        command: ["/bin/sh", "-c", "echo hello"]
      restartPolicy: Never
  backoffLimit: 4