apiVersion: batch/v1
kind: Job
metadata:
  name: serial-job
spec:
  completions: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: serialjobcontainer
        image: busybox
        command: ['sh', '-c']
        args: ['echo "Start Job!"; sleep 30; echo "Job Done!"']